### ISSUE TITLE
TODO Vulcan-Script

### ISSUE THREAD

**Issue by vulcan-dev** [vulcan-dev/kissmp-rp#1]
## Moderation Commands | Moderation
- [ ] Finish /mute command
- [ ] Finish /unmute command
- [ ] Finish /freeze command
- [ ] Finish /unfreeze command
- [ ] Finish /voteban command
- [ ] Finish /votekick command
- [ ] Finish /votemute command

## Utility Commands | Moderation
- [ ] Finish /time_play command
- [ ] Finish /time_stop command
- [ ] Finish /set_time command
- [ ] Finish /set_fog command
- [ ] Finish /tp command
- [ ] Finish /help command
- [ ] Finish /report command
- [ ] Finish /uptime command
- [ ] Finish /playtime command
- [ ] Finish /home command
- [ ] Finish /mods command
- [ ] Finish /discord command
- [ ] Finish /pm command
- [ ] Finish /block command
- [ ] Finish /unblock command
- [ ] Finish /donate command

## Fun Commands | Moderation
- [ ] Finish /imitate command
- [ ] Finish /set_gravity command
- [ ] Finish /destroy command

## Utility Commands | Roleplay
- [ ] Finish /me command
- [ ] Finish /do command
- [ ] Finish /repair command
- [ ] Finish /set_home command
- [ ] Finish /refuel command
- [ ] Finish /bank command

## API
- [ ] Send data to Discord (reporting, logging, user join, etc..)

## Other
- [ ] Add custom image for the loading screen
- [ ] Add music for the loading screen
- [ ] Fix extension reloading
- [ ] Make sure the ban system works
- [ ] Send data to the API
- [ ] Add voting
