### ISSUE TITLE
Milestone Utility Commands

### ISSUE THREAD

**Issue by vulcan-dev** [vulcan-dev/kissmp-rp#3]
## Vulcan-Moderation
- [ ] Finish /time_play command
- [ ] Finish /time_stop command
- [ ] Finish /set_time command
- [ ] Finish /set_fog command
- [ ] Finish /tp command
- [ ] Finish /help command
- [ ] Finish /report command
- [ ] Finish /uptime command
- [ ] Finish /playtime command
- [ ] Finish /home command
- [ ] Finish /mods command
- [ ] Finish /discord command
- [ ] Finish /pm command
- [ ] Finish /block command
- [ ] Finish /unblock command
- [ ] Finish /donate command

## Vulcan-RP
- [ ] Finish /me command
- [ ] Finish /do command
- [ ] Finish /repair command
- [ ] Finish /set_home command
- [ ] Finish /refuel command
- [ ] Finish /bank command
