### ISSUE TITLE
TODO Fun Commands

### ISSUE THREAD

**Issue by vulcan-dev** [vulcan-dev/kissmp-rp#4]
- [ ] Finish /imitate command
- [ ] Finish /set_gravity command
- [ ] Finish /destroy command
